### PR TITLE
Torch 2.1 installation instructions

### PR DESCRIPTION
**Pull request by carmocca**

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]

**Comment by Andrei-Aksionov** [comment]
FIY: by default, it installs with CUDA 12.1.
I quickly checked and looks like the quantization works.

**Comment by carmocca** [comment]
Good. Should we close https://github.com/Lightning-AI/lit-gpt/issues/455?

**Comment by Andrei-Aksionov** [comment]
Not yet. I'll do more testing and I'll put speed comparison (looks like the newest CUDA is faster, at least on T4 and Pythia-410m) into that issue. After that I'll close it.

P.S. It looks like CUDA 12.1 fixes also #593 but I need to do more testing.

**Comment by carmocca** [comment]
I have also noticed that 12.1 is ~15% faster in the scripts I've tried

**Comment by rasbt** [comment]
That's a nice free upgrade!

**Pull request merged**
