### PR TITLE
Sort table alphabetically by model name

### PR DESCRIPTION
**Pull request by rasbt**
This is definitely a matter of taste, but I think it will be easier to find the models in the table if the table is sorted alphabetically by model name rather than Org name. So, I changed "Org Name - Model Name" to "Model Name - Org Name" in the first column and sorted the table accordingly.

### CODE REVIEW

**Comment by Andrei-Aksionov** [comment]
Yes and no.
For me personally it's a bit more difficult to read simply because not all models have a link and thus there is a "visual break" in the list. 
If you add links to the three remaining models, then I will agree that this is better. At least link to their HF pages.

Btw, the first column is called "Model and usage". Shouldn't it be something like "Model and author"? Word "author" might not be the best fit, but "usage" is definitely is even worse.

**Review by carmocca — APPROVED** [review]
LGTM once Andrei's comment is addressed

**Comment by rasbt** [comment]
> If you add links to the three remaining models, then I will agree that this is better. At least link to their HF pages.

done


> Btw, the first column is called "Model and usage". Shouldn't it be something like "Model and author"? Word "author" might not be the best fit, but "usage" is definitely is even worse.


I think that table column header was because it was linking to the internal download and usage docs. Let's just call it "Model" for simplicity.

**Comment by Andrei-Aksionov** [comment]
Thanks Sebastian.

**Pull request merged**
