### PR TITLE
Codebase chores: typos, trailing spaces, markdown linting, Ruff and Black.

### PR DESCRIPTION
**Pull request by Andrei-Aksionov**
HI there 👋 

A simple chores PR comprised of:
1. VSCode's auto fix trailing spaces.
2. VSCode's Markdown lint: remove redundant empty lines and add surrounding ones where it's needed.
3. VSCode's cSpell: fix typos.
4. Small fix for the TinyLlama logger thing.
5. Ruff and Black.

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]

**Comment by Borda** [comment]
Shall we ass pre-commit to preserve this link of linting?

**Comment by Andrei-Aksionov** [comment]
> Shall we ass ...

Pardon? 🙂

----

The linting CLI command is already preserved here: https://github.com/Lightning-AI/lit-gpt/issues/758

**Comment by Borda** [comment]
> > Shall we ass ...
> 
> Pardon? 🙂

typo

> The linting CLI command is already preserved here: #758

I do not see any pre-commit config

**Comment by Andrei-Aksionov** [comment]
I updated the [comment](https://github.com/Lightning-AI/lit-gpt/issues/758#issuecomment-1862522682) so it includes the `.pre-commit-config.yaml` that I use.
There are two moments:
1. Black and/or Ruff might provide different formatting when it runs as CLI command in comparison to VSCode extension or pre-commit hook, so the decision was made to stick to CLI command, thus in the pre-commit the hook calls CLI command.
2. Lit-GPT doesn't contain any linter config, thus it's all voluntary. I did it for myself, so I don't forget to format the code when working on a PR. Carlos from time-to-time runs linter and commits changes. I tried to create a CI job that doesn't rely on a config (#765), but there was a problem that jobs weren't restarted if the code was automatically formatter, unless PAT was used.

**Pull request merged**
