### PR TITLE
Fix relative import in tests

### PR DESCRIPTION
**Pull request by Andrei-Aksionov**
Hi there 👋 

There is a problem with importing files from `reference_model` folder.
Since this issue can plague all the newest PRs, I decided to create a separate one with the fix.

### CODE REVIEW

**Review by carmocca — APPROVED** [review]
I don't understand why this pops up now

**Comment by Andrei-Aksionov** [comment]
I also don't understand.
On my local machine I don't have such a problem. In an older Studio I also got such an error, but not on a newer Studio.
¯\_(ツ)_/¯

**Comment by carmocca** [comment]
You dropped this: \\

**Comment by Andrei-Aksionov** [comment]
Markdown formatting.
It turned out you need 3 backshales:
¯\\\_(ツ)_/¯

image

**Pull request merged**
