### PR TITLE
Enable Python 3.8 testing

### PR DESCRIPTION
**Pull request by carmocca**

### CODE REVIEW

**Comment by carmocca** [comment]
I couldnt get this to work

**Comment by Andrei-Aksionov** [comment]
> I couldnt get this to work

Because it's not possible.
As I stated in #632 Python 3.8 [isn't supported](https://github.com/EleutherAI/lm-evaluation-harness/blob/008fc2a23245c40384f2312718433eeb1e0f87a9/setup.py#L24) by `lm-eval`.
It's possible to install packages by providing the latest supported by 3.8 packages in requirements-all.txt:
```yaml
-r requirements.txt
bitsandbytes==0.41.0    # quantization
scipy~=1.10.1           # required by bitsandbytes
sentencepiece           # pythia, falcon, redpajama
tokenizers~=0.15.0      # llama-based models
datasets                # quantize/gptq.py
zstandard               # scripts/prepare_redpajama.py, scripts/prepare_starcoder.py
pandas~=2.0.3           # scripts/prepare_csv.py, scripts/prepare_starcoder.py
transformers~=4.35.2
pyarrow                 # scripts/prepare_starcoder.py
# eval
git+https://github.com/EleutherAI/lm-evaluation-harness.git@master
# scripts/prepare_slimpajama.py, scripts/prepare_starcoder.py, pretrain/tinyllama.py
lightning[data] @ git+https://github.com/Lightning-AI/lightning@532c723c8584903dc719458d0ad52861d51bc395
```

... but it doesn't matter as in the end you get the final error:
```python
ERROR: Package 'lm-eval' requires a different Python: 3.8.18 not in '>=3.9'
```

**Comment by Andrei-Aksionov** [comment]
Don't know what is wrong with me, but when someone says that it's not possible, it triggers me, and I want to prove that it's indeed possible. In this case, I triggered myself 🙈. 

So, yes, it's possible. But you have to provide `--ignore-requires-python` to force to install `lm-eval` and that argument requires fixing even more packages.
But at least it works: https://github.com/Andrei-Aksionov/lit-gpt/pull/1
Too hacky for my liking though.

**Comment by carmocca** [comment]
Thank you @Andrei-Aksionov! I didn't know that lm eval is >=3.9. Pip is weird, it should mention this before going down the rabbit hole of trying different dependency combinations

**Comment by Andrei-Aksionov** [comment]
Glad that I was helpful.

Your solution is much nicer, btw 👍

**Comment by Andrei-Aksionov** [comment]
A new twist: now `lm-eval` [supports](https://github.com/EleutherAI/lm-evaluation-harness/pull/1004) python 3.8 😆.

**Pull request merged**
